### ISSUE TITLE
Too many faggots with write rights

### ISSUE THREAD

**Issue by s0r00t** [s0r00t/yaf.js#2]

**Comment by frainfreeze** [comment]
shiet, someone might actually push some code!

**Comment by edocod** [comment]
Please refrain from using the word faggot. Please use the term "non heterosexual person" or "homosexual people". This highly triggers me and i just want to kill themselves.

**Comment by s0r00t** [comment]
or you could just kill yourself that would definitely save the world once and for all.

**Comment by frainfreeze** [comment]
![10632872_276984665838047_1269561684986823994_n](https://cloud.githubusercontent.com/assets/8762609/12278976/8e4957d8-b984-11e5-8444-f3fb43d7c20e.jpg)
CODE WAS PUSHED TO ASM BRANCH, case closed, we fukked up.

**Comment by samis** [comment]
@edocod perhaps considering detecting/removing obviously evil Offensive And Triggering language using https://github.com/wooorm/alex

**Comment by frainfreeze** [comment]
We don't use other js libraries, if you need it, make it.

**Comment by s0r00t** [comment]
DEPENDENCES ARE TOO FILTHY FOR GLORIOUS COMMUNISM
