### ISSUE TITLE
Mysognist!

### ISSUE THREAD

**Issue by edocod** [s0r00t/yaf.js#3]
Please refrain from using the combination of words "yet another". Frameworks should be equally respected and this one doesn't deserve to be called "yet another".

Also, the main file "readme" oppresses me since it obligated me to read it. Also, i sexually identify myself as a strawberry (I'm strawberry-kin). Refrain from using gendered pronouns like "he" or "she": instead use non-triggering ones like "them" or "they".

-------------------------------------------------

Th. Edocod
Warrior in Social Justice

**Comment by s0r00t** [comment]
Are you claiming that frameworks aren't free to choose their gender?

**Comment by frainfreeze** [comment]
This is offensive and does not help to the development.

**Comment by edocod** [comment]
> Are you claiming that frameworks aren't free to choose their gender?
Stop oppressing me. Use they/them instead of you.

> This is offensive and does not help to the development.
Did you check your privilege you cis scum?

**Comment by frainfreeze** [comment]
![1959406_996735590352430_304316657556360812_n](https://cloud.githubusercontent.com/assets/8762609/12278859/d282216a-b983-11e5-9282-4e1c932f0ab2.jpg)
